[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "aarch64.json"

[target.aarch64.json]
rustflags = "-C link-arg=-Tkernel.ld"
linker = "rust-lld"
